apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: acp
  namespace: kit-platform-1 # {"$kpt-set":"platform-project"}
  annotations:
    gke.io/cluster: bootstrap://
spec:
  location: us-central1 # {"$kpt-set":"location"}
  workloadIdentityConfig:
    identityNamespace: kit-platform-1.svc.id.goog # {"$kpt-set":"acp-identity"}
